class Producto
    {
        Id;
        Nombre;
        Ingredientes;
        Cantidad;
        CantMeGusta;
        Marca;
        EspeciesAmenazadas;
        HCAgricultura;
        HCProcesado;
        HCEmbalaje;
        HCTransporte;
        HCDistribución;
        HCConsumo;
        HCTotal;
        NAlcohol100g;
        NCarbohidratos100g;
        NEnergia100g;
        NGrasa100g;
        NFibra100g;
        NProteinas100g;
        NSal100g;
        NGrasasSaturadas100g;
        NSodio100g;
        NAzucar100g;
        Foto;
    }
    export default Producto;